{
 "title": "Akka.NET Cluster + Phobos Metrics (Influx Data Source)",
 "description": "System-wide Akka.Cluster metrics used for profiling Akka.NET performance",
 "tags": [
  "akka.net",
  "phobos"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "tags", "query": "SHOW TAG KEYS" },
   {
    "name": "role",
    "label": "Role",
    "query": "SHOW TAG VALUES WITH KEY=\"cluster_role\""
   },
   {
    "name": "address",
    "label": "address",
    "query": "SHOW TAG VALUES  WITH KEY = \"akka_address\" "
   }
  ]
 },
 "panels": [
  { "title": "Cluster Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active Cluster Size",
   "type": "stat",
   "description": "Total number of active Akka.Cluster Members.",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Up",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "akka.net__akka.cluster.members",
     "query": "SELECT CEIL(*) FROM (SELECT mean(\"value\") FROM \"akka.net__akka.cluster.members\" WHERE (\"status\" = 'Up') AND time >= now() - 30s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "ceil(value)" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "Up" }
     ]
    },
    {
     "alias": "WeaklyUp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "akka.net__akka.cluster.members",
     "query": "SELECT CEIL(*) FROM (SELECT mean(\"value\") FROM \"akka.net__akka.cluster.members\" WHERE (\"status\" = 'WeaklyUp') AND time >= now() - 30s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "WeaklyUp" }
     ]
    },
    {
     "alias": "Joining",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "akka.net__akka.cluster.members",
     "query": "SELECT CEIL(*) FROM (SELECT mean(\"value\") FROM \"akka.net__akka.cluster.members\" WHERE (\"status\" = 'Joining') AND time >= now() - 30s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "Joining" }
     ]
    },
    {
     "alias": "Leaving",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "akka.net__akka.cluster.members",
     "query": "SELECT CEIL(*) FROM (SELECT mean(\"value\") FROM \"akka.net__akka.cluster.members\" WHERE (\"status\" = 'Leaving') AND time >= now() - 30s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "Leaving" }
     ]
    },
    {
     "alias": "Exiting",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "akka.net__akka.cluster.members",
     "query": "SELECT CEIL(*) FROM (SELECT mean(\"value\") FROM \"akka.net__akka.cluster.members\" WHERE (\"status\" = 'Exiting') AND time >= now() - 30s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "Exiting" }
     ]
    },
    {
     "alias": "Down",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "akka.net__akka.cluster.members",
     "query": "SELECT CEIL(*) FROM (SELECT mean(\"value\") FROM \"akka.net__akka.cluster.members\" WHERE (\"status\" = 'Down') AND time >= now() - 30s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "Down" }
     ]
    }
   ]
  },
  {
   "title": "Unreachable Nodes",
   "type": "stat",
   "description": "All nodes in the cluster that are detected to be unreachable.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "akka.net__akka.cluster.reachable",
     "query": "SELECT CEIL(*) FROM (SELECT mean(\"value\") FROM \"akka.net__akka.cluster.reachable\" WHERE (\"reachable\" = 'false') AND time >= now() - 30s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "reachable", "operator": "=", "value": "false" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Nodes by Status",
   "type": "graph",
   "description": "Tracks all nodes by their membership status and reachability.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_status]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "status" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "akka.net__akka.cluster.members",
     "query": "SELECT max(\"value\") FROM \"akka.net__akka.cluster.members\" WHERE $timeFilter GROUP BY time($__interval), \"status\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Unreachable",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "akka.net__akka.cluster.reachable",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Logging and Error Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Cluster Logging Activity",
   "type": "graph",
   "description": "Total aggregate logging activity per-second for each node in an Akka.NET cluster.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "[[tag_level]]",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "level" ], "type": "tag" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "akka.net__akka.logs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_role", "operator": "=~", "value": "/^$role$/" },
      { "condition": "AND", "key": "akka_address", "operator": "=~", "value": "/^$address$/" }
     ]
    }
   ]
  },
  {
   "title": "Exceptions by Type",
   "type": "table",
   "description": "Groups all exceptions detected in Akka.NET logs by type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "exceptiontype" ], "type": "tag" },
      { "params": [ "akka_address" ], "type": "tag" },
      { "params": [ "cluster_role" ], "type": "tag" }
     ],
     "measurement": "akka.net__akka.logs",
     "query": "SELECT count(\"value\") FROM \"akka.net__akka.logs\" WHERE (\"cluster_role\" =~ /^$role$/ AND \"akka_address\" =~ /^$address$/ AND \"exceptiontype\" =~/[.]/) AND $timeFilter GROUP BY \"exceptiontype\", \"akka_address\", \"cluster_role\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "cluster_role", "operator": "=~", "value": "/^$role$/" },
      { "condition": "AND", "key": "akka_address", "operator": "=~", "value": "/^$address$/" },
      {
       "condition": "AND",
       "key": "exceptiontype",
       "operator": "=",
       "value": "\".+\""
      }
     ]
    }
   ]
  },
  {
   "title": "Total Errors Logged",
   "type": "stat",
   "description": "Total errors logged by Akka.NET over past 5 minutes, cumulative for all roles / cluster / exception types.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Errors",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "akka.net__akka.logs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "level", "operator": "=", "value": "error" },
      { "condition": "AND", "key": "akka_address", "operator": "=~", "value": "/^$address$/" },
      { "condition": "AND", "key": "cluster_role", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  { "title": "Actor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Total Akka.NET Actors",
   "type": "graph",
   "description": "The full set of Akka.NET actors running on all nodes for all roles in a cluster.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Alive Actors  [ [[tag_cluster_role]] ([[tag_akka_address]])]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "akka_address" ], "type": "tag" },
      { "params": [ "cluster_role" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "akka.net__akka.actor.created",
     "query": "SELECT sum(\"value\") FROM \"akka.net__akka.actor.created\" WHERE (\"cluster_role\" =~ /^$role$/ AND \"akka_address\" =~ /^$address$/) AND $timeFilter GROUP BY \"akka_address\", \"cluster_role\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_role", "operator": "=~", "value": "/^$role$/" },
      { "condition": "AND", "key": "akka_address", "operator": "=~", "value": "/^$address$/" }
     ]
    },
    {
     "alias": "Terminated Actors  [ [[tag_cluster_role]] ([[tag_akka_address]])]",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "akka_address" ], "type": "tag" },
      { "params": [ "cluster_role" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "akka.net__akka.actor.stopped",
     "query": "SELECT sum(\"value\") FROM \"akka.net__akka.actor.stopped\" WHERE (\"cluster_role\" =~ /^$role$/ AND \"akka_address\" =~ /^$address$/) AND $timeFilter GROUP BY \"akka_address\", \"cluster_role\" fill(linear)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_role", "operator": "=~", "value": "/^$role$/" },
      { "condition": "AND", "key": "akka_address", "operator": "=~", "value": "/^$address$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Actor Throughput (msg/s)",
   "type": "stat",
   "description": "Cumulative Akka.NET messaging throughput across all selected nodes and roles.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "akka.net__akka.messages.recv",
     "select": [
      [
       { "params": [ "rate.mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cluster_role", "operator": "=~", "value": "/^$role$/" },
      { "condition": "AND", "key": "akka_address", "operator": "=~", "value": "/^$address$/" }
     ]
    }
   ]
  },
  {
   "title": "Live Actors by Type (Top 10)",
   "type": "table",
   "description": "Top 10 actor starts / stops by type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "alias": "[[tag_actortype]] created",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "actortype" ], "type": "tag" }
     ],
     "measurement": "akka.net__akka.actor.created",
     "query": "SELECT count(\"value\") AS \"Created\" FROM \"akka.net__akka.actor.created\" WHERE (\"akka_address\" =~ /^$address$/ AND \"cluster_role\" =~ /^$role$/) GROUP BY time(5m), \"actortype\" LIMIT 10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Created" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "akka_address", "operator": "=~", "value": "/^$address$/" },
      { "condition": "AND", "key": "cluster_role", "operator": "=~", "value": "/^$role$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "actortype" ], "type": "tag" }
     ],
     "measurement": "akka.net__akka.actor.stopped",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "Terminated" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "akka_address", "operator": "=~", "value": "/^$address$/" },
      { "condition": "AND", "key": "cluster_role", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "Actor Crashes by Actor / Exception (Top 10)",
   "type": "table",
   "description": "Top 10 actor type / exception type pairs, based on the number of crashes per second observed over a 30 minute timespan.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "actortype" ], "type": "tag" },
      { "params": [ "exceptiontype" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": 10,
     "measurement": "akka.net__akka.actor.restarts",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Akka.NET Message Throughput by Type  (Top 10)",
   "type": "bargauge",
   "description": "Akka.NET message throughput by message type.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "[[tag_messagetype]]",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "messagetype" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": 10,
     "measurement": "akka.net__akka.messages.recv",
     "query": "SELECT mean(\"rate.mean\") FROM \"akka.net__akka.messages.recv\" WHERE (\"akka_address\" =~ /^$address$/ AND \"cluster_role\" =~ /^$role$/) AND $timeFilter GROUP BY time(5m), \"messagetype\" fill(null) LIMIT 10",
     "select": [
      [
       { "params": [ "rate.mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "akka_address", "operator": "=~", "value": "/^$address$/" },
      { "condition": "AND", "key": "cluster_role", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  },
  {
   "title": "Akka.NET Message Totals by Type  (Top 10 over 5 minutes)",
   "type": "bargauge",
   "description": "Akka.NET message throughput by message type.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "[[tag_messagetype]]",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" },
      { "params": [ "messagetype" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "limit": 10,
     "measurement": "akka.net__akka.messages.recv",
     "select": [
      [
       { "params": [ "count.meter" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "akka_address", "operator": "=~", "value": "/^$address$/" },
      { "condition": "AND", "key": "cluster_role", "operator": "=~", "value": "/^$role$/" }
     ]
    }
   ]
  }
 ]
}