version: '3.7'

services:
  seq:
    image: datalust/seq:2020.5
    hostname: seq
    restart: always
    ports:
      - '8988:80'
    environment:
      - ACCEPT_EULA=Y

  grafana:
    image: grafana/grafana:7.3.7
    restart: always
    ports:
      - '3000:3000'
    links:
      - graphite
    environment:
      - GF_AUTH_BASIC_ENABLED=true
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - ./grafana/datasource:/etc/grafana/provisioning/datasources
      - ./grafana/providers:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboard:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana

  influxdb:
    image: influxdb:1.8
    restart: always
    ports:
      - '8086:8086'
      - '2003:2003'
    environment:
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    volumes:
      - influxdb-data:/influxdb

  jaeger:
    image: jaegertracing/all-in-one
    hostname: jaeger
    restart: always
    ports:
      - '5775:5775/udp'
      - '5778:5778'
      - '6831:6831/udp'
      - '6832:6832/udp'
      - '9411:9411'
      - '14267:14268'
      - '14268:14250'
      - '16686:16686'
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

volumes:
  influxdb-data:
    external: false
  grafana-data:
    external: false    